project:
  type: website
  # output-dir: docs # Put output into docs folcer instead of _site

website:
  title: "DSCI 310 Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

#
editor: 
  render-on-save: true

